# Файл с конфигурацией линтера
# ============================

# Максимальная длина строки кода
line-length = 79

# Ширина отступа
indent-width = 4

# Указывает целевую версию Python (в данном случае 3.11)
target-version = "py311"

# Исключает из проверки определённые файлы и папки
extend-exclude = ["migrations", "__pycache__", "manage.py", "settings.py", ".venv", "venv"]

[format]
# Одинарные кавычки
quote-style = "single"

# Стиль отступов — пробел
indent-style = "space"

[lint]
# Расширяет выбор включенных проверок.
# "I" — Упорядочивание импортов (isort).
# "F" — Ошибки типа (flake8).
# "B" — Проверка best practices (bugbear).
# "E" — Проверка стиля PEP 8.
# "N" — Проверка стиля именования.
extend-select = ["I", "F", "B", "E", "N"]
